### ISSUE TITLE
Amazon アソシエイトのブロック解除

### ISSUE THREAD

**Issue by hirorpt** [hirorpt/filters#1]
### 問題の起こるURL
`https://eman-physics.net/relativity/birth.html`
### 問題の説明
アフィリエイト広告は消すと文章の意味がわからなくなることがある。特に以下のスクリーンショットのようなウィジェットはその傾向が強いようだ。とりあえず一般許可したが、調査すべきことが多い。

### スクリーンショット
![Image](https://user-images.githubusercontent.com/82331005/122666489-7b871400-d1e8-11eb-97c8-994595a8be14.png)

### 備考
- ウェブサイトのメインコンテンツと全く関係のない広告まで許可していないか
- このウィジェットはどうやって生成されたものか
- 280blockerではそもそもブロック対象にならないようだ。どちらの方式が秀れているか調査したい
- 海外サイトではこのウィジェットは使われているか
- どうやってELと交渉するか
- 類似のELフィルタ`@@||amazon-adsystem.com/widgets/q?$image`について
初出?: https://github.com/easylist/easylist/commit/603aefd `https://forums.lanik.us/viewtopic.php?f=64&t=23627`
削除: https://github.com/easylist/easylist/commit/be15ad9
再導入: https://github.com/easylist/easylist/commit/a6d88f2 `https://github.com/easylist/easylist/issues/3660`
削除: https://github.com/easylist/easylist/commit/f88b9fc `https://old.reddit.com/r/uBlockOrigin/comments/ghjqph/camazonadsystemcomaax2apstagjsscript/`
再導入: https://github.com/easylist/easylist/commit/0e6fd82 `https://github.com/easylist/easylist/issues/3686`
削除: https://github.com/easylist/easylist/commit/17576f1
再導入: https://github.com/easylist/easylist/commit/2c7da8b `https://github.com/easylist/easylist/issues/5344`
削除: https://github.com/easylist/easylist/commit/e42abfc
再導入: https://github.com/easylist/easylist/commit/7305ef4
- 必須のパラメータ４つ
~~~
! asins 以外は他の広告ウィジェットでも出現。l は他では中身が違うようであり識別に使用できるかも
||ws-fe.assoc-amazon.com/widgets/cm?*&asins=$subdocument,removeparam=~/^asins=|^l=|^o=|^t=/
||rcm-fe.amazon-adsystem.com/e/cm?*&asins=$subdocument,removeparam=~/^asins=|^l=|^o=|^t=/
||rcm-jp.amazon.co.jp/e/cm?*&asins=$subdocument,removeparam=~/^asins=|^l=|^o=|^t=/
~~~
### 追加したフィルタ
~~~
@@||rcm-fe.amazon-adsystem.com/e/cm?*&asins=$subdocument
@@||ws-fe.assoc-amazon.com/widgets/cm?*&asins=$subdocument
@@||wms-fe.amazon-adsystem.com/panda/20070822/US/img/cart.gif$image,domain=ws-fe.assoc-amazon.com
@@||wms-fe.amazon-adsystem.com/panda/20070822/JP/img/a-logo-amazon.png$image,domain=ws-fe.assoc-amazon.com
@@||wms-fe.amazon-adsystem.com/panda/20070822/US/img/prime.png$image,domain=ws-fe.assoc-amazon.com
~~~

**Comment by tofukko** [comment]
これも必要
`@@||rcm-*.amazon.*/e/cm?*&asins=$subdocument`
`http://www5c.biglobe.ne.jp/~nyu/BOOK/20130601BOOK.htm`

**Comment by Yuki2718** [comment]
この場合はまとめるより
`||rcm-jp.amazon.co.jp/e/cm?*&asins=$subdocument`
を追加したほうがuBOではパフォーマンスがよくなります。ただ、海外で`-fe`以外のパターンがあるなら総合的にはまとめたほうがいいかもしれません。
