### ISSUE TITLE
AdGuard Japaneseのgeneral_urlを見直す

### ISSUE THREAD

**Issue by hirorpt** [hirorpt/filters#6]
やりきるかは別として、とりあえず場所は用意しておく
参考: [AdGuard Japanese filter (Optimized)](https://filters.adtidy.org/extension/ublock/filters/7_optimized.txt), [EasyList (Optimized)](https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt),[EasyList](https://filters.adtidy.org/extension/ublock/filters/101.txt)

| | 高 | 中 | 低 | 無 |
|- |----|-----|-----|----|
|有用度 |ある種のプラグイン/広告に特有|複数のサイトで有効性を確認|ごく限られたサイトで有効性を確認 / 未確認だが有用なブロックがある可能性が高い|何をブロックしているのかが不明|
|危険度|allowlistの個別対応が現実的ではない|いくつかの誤爆がある|誤爆があってもおかしくない|誤爆することは考えにくい|

|   | 追加コミット|有用度 | 危険度| 備考 |
|---|--------|--------|--------------|------|
| `/plugins/betube-ads/*` |[AG@4033df3](https://github.com/AdguardTeam/AdguardFilters/commit/4033df3)|||EL/Base向けでは？|
| `.com/ufo/$script,third-party` |[AG@78a0e60](https://github.com/AdguardTeam/AdguardFilters/commit/78a0e60)|高|低|[ABPJF 2010年の更新履歴](https://code.google.com/archive/p/adblock-plus-japanese-filter/wikis/FilterChangeLog2010.wiki)|
| `.com/Zen?` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)|||[ABPJF 2010年の更新履歴](https://code.google.com/archive/p/adblock-plus-japanese-filter/wikis/FilterChangeLog2010.wiki)|
| `.jp/affiliate/$third-party` |[AG@199fd32](https://github.com/AdguardTeam/AdguardFilters/commit/199fd32)||||
| `.jp/html.ng/` ||||[ABPJF 2010年の更新履歴](https://code.google.com/archive/p/adblock-plus-japanese-filter/wikis/FilterChangeLog2010.wiki)|
| `.jp/image/ad/` |||||
| `.jp/log.php?` |||||
| `.jp/ufo/$script,third-party` |[AG@43e2eaa](https://github.com/AdguardTeam/AdguardFilters/commit/43e2eaa)|高|低|[ABPJF 2010年の更新履歴](https://code.google.com/archive/p/adblock-plus-japanese-filter/wikis/FilterChangeLog2010.wiki)|
| `.jp/Zen?` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)|||[ABPJF 2010年の更新履歴](https://code.google.com/archive/p/adblock-plus-japanese-filter/wikis/FilterChangeLog2010.wiki)|
| `/__sys__inactive_message.js` |[AG@71bfbdd](https://github.com/AdguardTeam/AdguardFilters/commit/71bfbdd)|高|無|忍者ホームページの更新停止広告|
| `/ad?cid=` ||||ELとの重複|
| `/ad_bomb/*` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)||||
| `/ad_parts.` |[FJ@11057bc](https://github.com/ryanbr/fanboy-adblock/commit/11057bc)||||
| `/ad_timer.` ||||`*/ad_timer.js`として[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)|
| `/adcast01_` |[FJ@9e4714b](https://github.com/ryanbr/fanboy-adblock/commit/9e4714b)||||
| `/adContents_` |||||
| `/adgetter.` |||||
| `/adparts/*` |||||
| `/adSidebar.` |[FJ@82f7ede](https://github.com/ryanbr/fanboy-adblock/commit/82f7ede)||||
| `/advalue_` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)||||
| `/banimg/*` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)||||
| `/images/tamakuri` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)|||[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)には`*/tamakuri80x35.jpg`というフィルタも|
| `/js/dlvRequest.` |[AG@e6a7cb](https://github.com/AdguardTeam/AdguardFilters/commit/fe6a7cb)||||
| `/js/dlvRequest_` |[AG@e6a7cb](https://github.com/AdguardTeam/AdguardFilters/commit/fe6a7cb)||||
| `/js/fix_ad.js?` |[AG@b2daf9c](https://github.com/AdguardTeam/AdguardFilters/commit/b2daf9c)||||
| `/js/ulizahtml5-advertising.` |[AG@b3c3648](https://github.com/AdguardTeam/AdguardFilters/commit/b3c3648)|高|無|Token化されるのだろうか。scriptつけたほうが良いのかも？|
| `/parts/ad/*` |[FJ@82f7ede](https://github.com/ryanbr/fanboy-adblock/commit/82f7ede)||||
| `/TextAD1.` |[FJ@cf42898](https://github.com/ryanbr/fanboy-adblock/commit/cf4289847c)|||`*/TextAD1.aspx`として[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)|
| `/top/head_bnr` |[FJ@cca1382](https://github.com/ryanbr/fanboy-adblock/commit/cca1382)||||
| `/openstrap/js/meerkat_side_double_ad.js` |[AG@ab23352](https://github.com/AdguardTeam/AdguardFilters/commit/ab23352)||||

**Comment by Yuki2718** [comment]
```
.jp/js.ng/cat=
/beacon.php3?
/images/gban/*
/popjs.asp
/random_bnr/*
/banana/600x
/mini_ads.php?
_ds_adtag_
```
この辺はAGのテレメトリ統計でhitが0なので、クリーンアップとして削除することもできそうです。

**Comment by hirorpt** [comment]
> AGのテレメトリ統計
Yukiさんが特別にアクセス権与えられていて、普通の人は見れないものって認識であってます？
Optimizedフィルタにあるかどうかを見れば代替になると思っていたのですが、0hitというルールも普通に残ってますね。

**Comment by Yuki2718** [comment]
合ってますが私も自由にアクセスできるわけではないです。Optimizedはリストごとに圧縮率が設定されていて、もともと小さいJPNなどの場合はほとんど圧縮していないと思います。
よく考えたら個別の場合はいるかいらないか自明なので直接削除すればいいわけで、PRはgenericに限ろうと思います。ところで
```
@@||*.club/sc?u=
@@||*.info/sc?u=
```
ってなぜ追加されたかトラックできますか？マイナーTLDとはいえちょっと雑な気が・・

**Comment by hirorpt** [comment]
> ってなぜ追加されたかトラックできますか？

`rule update avgle` とのことです。なんでドメイン指定してないんだろう
https://github.com/AdguardTeam/AdguardFilters/commit/0cbfead

**Comment by Yuki2718** [comment]
ありがとうございます、これもいらなさそうですね。
