### ISSUE TITLE
YouTubeの再生履歴

### ISSUE THREAD

**Issue by hirorpt** [hirorpt/filters#8]
YouTube見ないので分からん。uBOで報告されているので、既知のABPJFの問題ではない。
~~EasyPrivacyが原因という話もある(uBOの報告例が多いのでたしかに怪しい)。~~ よく読んだらEPオンで治ったというツイだった
豆腐フィルタユーザが3人中少なくとも2人で怪しい。

`https://twitter.com/yamatanoorotii/status/1406967745820778499`
`https://twitter.com/nagamasa33/status/1406874352050601987`
`https://twitter.com/nayuta_sw/status/1406224640498880519`

**Comment by hirorpt** [comment]
YouTube Issueは問題なら誰かが動くはずなので、自分は関知しない
ただ最近、再生履歴不具合の声をよく見かけるようになったということを記録しておく。

**Comment by Yuki2718** [comment]
標準と標準＋豆腐でログインあり、なしともにこちらでは異常ないですね。FirefoxでもChromeでも同じです。（プログレスバーを再生履歴と言うのだろうか？
