### ISSUE TITLE
フィルター議論/連絡用スレッド

### ISSUE THREAD

**Issue by hirorpt** [hirorpt/filters#9]
コミットにコメントつけて@Yuki2718さんに連絡してきましたが、検索性が低くなるため原則こちらのスレッドに移行します。

フィルタに関する話題ならば誰でも書き込んで結構です。

**Comment by hirorpt** [comment]
@Yuki2718
Unbreak の`/RequestVideoTag.$badfilter`はもう不要のはずです。

Cxenseは標準フィルタでもブロック対象外であってほしいと思うのですが、どう思われます？

**Comment by Yuki2718** [comment]
> Unbreak の`/RequestVideoTag.$badfilter`はもう不要のはずです。

削除しました。

> Cxenseは標準フィルタでもブロック対象外であってほしいと思うのですが、どう思われます？

[これ](https://forums.lanik.us/viewtopic.php?f=64&t=45816)があるのでEPからは削除されないと思います。AGにも来ていた気がしたんですが、検索にかからないので別のリコメンド業者と勘違いしているかもしれません。

**Comment by hirorpt** [comment]
> 削除しました。
ulizaのnoopjsリダイレクトが3つ入ってますがこれもすでに不要に見えます。

> これがあるのでEPからは削除されないと思います。

具体的なURLも提示せず、破損したサイトオーナー自身の要求ということで、もう少し丁寧に説明に第三者が説明すれば少しは可能性がありそうな気もしますが。
ただ徒労に終わる可能性が高いのに頑張って説明するのはめんどくさい......。Unbreakに入れられないかという点でryanbrよりgorhillの意見が知りたいですね。EPに言えよと言われる気もしますが。


雪にhttps://github.com/hirorpt/filters/issues/1 で挙げたURL の例外はいれないのですか？

**Comment by hirorpt** [comment]
私はryanbrをsensibleなフィルタ作者だと思ってない<sup>1</sup>ので、微妙な案件はELのリポジトリで議論したくないなというのが本音です。
Yukiさんの独断で入れるには影響が大きすぎるのでそれは全く求めませんが、Uassetsのメンテナで議論してgorhillがUnbreakに入れるかどうか決めてくれればいいのになと思ってます。
https://github.com/easylist/easylist/pull/7905
https://github.com/uBlockOrigin/uBlock-issues/issues/738

<details>
<summary>1</summary>
<sub>1:  <code>for generic filters, the burden of proof is reversed and first on filter list maintainers (uBlockOrigin/uBlock-issues#738)</code>と正論を言える人と、<code>remove generic blocks, why. (easylist/easylist#7905)</code>でcloseしてもう一度丁寧に説明しても無視する人を比べたらだな.......</sub>
</details>

**Comment by Yuki2718** [comment]
> 
> ulizaのnoopjsリダイレクトが3つ入ってますがこれもすでに不要に見えます。

後ほど確認し、不要なら削除しておきます。

uAssetsは標準リストを補助する位置づけなので、ELでまず議論されるのが理想ではあります。もっとも、ちゃんとみてくれないという不満はhirorptさんに限ったことではなく、古参contributorのTHEtomaso氏などもよく口にしています。説明でがんばるよりURLの数とスクショで攻めたほうがいいかもしれません。Cxenseを買収したPianoのブロックは多数の不具合が見つかった結果調整されているので、Cxenseも多くの不具合を根拠にIssueを立てれば見込みはあると思うのですが、私自身は日本のサイトの不具合しか知りませんし、それも今のところまだ限定的なので、これくらいだとEPは例外で対処するよなあという気はしています。

憶測ですが、他メンテナーのリストなどを見ても、この世代のフィルタ作成においてはgenericを使うのは割と普通のことだったのかなという気がします。今とはネットの状況もブロッカーユーザーも違っていたでしょうし。私も以前はよく[愚痴って](https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-591218779)いましたが、結局、ELとはうまく付き合わざるを得ないと思っています。公私ともに、雪では対象外のサイトもよく使いますし。

> 
> 雪に#1 で挙げたURL の例外はいれないのですか？

eman-physicsでしたら関連性が低い（「ゲームのサイトだからゲームの広告」レベル）と判断しました。もともとこのサイトは広告がなく、数年前から広告を貼りだしたと記憶しています。

**Comment by hirorpt** [comment]
> ELでまず議論されるのが理想ではあります

これは個人的な考えで、あまり同意されるものではないでしょうが(英語でどっかに書き込んだらめっちゃdownvote付きそう)
Medium mode が用意されているuBOと、フィルター以上のことはできない他のブロッカーでも使用されるEPでは、トラッキングブロックに対する方針が違ってていい、EP以上に不具合に敏感でも良いのではと思ってます。Peter Loweへのbadfilterが大量にublock filtersに入っているのと同じように。

> 私自身は日本のサイトの不具合しか知りませんし、それも今のところまだ限定的なので

大雪で対応していないものだと、翔泳社`shoeisha.co.jp`, `seshop.com`で見かけました。
AGTPFだといくつか海外向け例外ルールがありますね
